version: '3.8'

services:
  appmimetismo:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g